### ISSUE TITLE
README.md has dead link to forum

### ISSUE THREAD

**Issue by Billfred** [makersmakingchange/PVC-Accessible-Mounting-System#2]
The link to the forum thread goes nowhere, presumably due to an old link that didn't get a redirect.

I'm making a baseless guess that it's trying to reach https://makersmakingchange.com/forum/topic/pvc-assistive-mounting-system-2/ but have no firsthand knowledge as someone late to the party.

**Comment by Billfred** [comment]
To be precise, https://github.com/makersmakingchange/PVC-Accessible-Mounting-System/README.md is the page with this issue.  Sorry about that!

**Comment by jakemcivor** [comment]
Thanks. We're slowly updating all of the repositories with updated forum links.
